/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ball_ring3.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BgModel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/ball_ring3.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions["TorusAction"].play()
    actions["TorusAction.001"].play()
    actions["TorusAction.002"].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} scale={1.608}>
          <meshLambertMaterial color={0xffffff}/>
        </mesh>
        <mesh name="Torus" geometry={nodes.Torus.geometry} scale={4.511} >
          <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={3}/>
          <directionalLight color={'orange'} intensity={5} distance={5}/>
        </mesh>
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} scale={-3.874} >
          <meshStandardMaterial color={'red'} emissive={'red'} emissiveIntensity={10}/>
          <directionalLight color={'red'} intensity={10} distance={5}/>
        </mesh>
        <mesh name="Torus002" geometry={nodes.Torus002.geometry} scale={-3.24} >
          <meshStandardMaterial color={0x69247c} emissive={0x69247c} emissiveIntensity={20}/>
          <directionalLight color={0x69247c} intensity={20} distance={5}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/ball_ring3.glb')
