/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Sakura_Tree_7.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { SpotLightHelper } from 'three'

export function SakuraTree(props) {
  const { nodes, materials } = useGLTF('./models/Sakura_Tree_7.glb')
  const light = useRef()
  // useHelper(light, SpotLightHelper, "red")

  const GrassTexture = useTexture({
    map: './textures/grass/grass_diff.jpg',
  })
  // const WoodTexture = useTexture({
  //   map: './textures/wood/wood_diff.jpg',
  //   displacementMap: './textures/wood/wood_disp.png',
  // })

  const RoadTexture = useTexture({
    map: './textures/road/road_diff.jpg',
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree.geometry} material={materials['Tree Bark.001']} position={[0, 6.88, 0]} scale={5}>
        <mesh geometry={nodes.leaves.geometry} material={nodes.leaves.material}>
          <meshStandardMaterial color={'hotpink'} emissive={'hotpink'} emissiveIntensity={15}/>
          <spotLight ref={light} color={'hotpink'} intensity={2000} angle={2} position={[0, 10, 0]}/>
          <pointLight color={'hotpink'} intensity={2000}/>
        </mesh>
      </mesh>
      <mesh geometry={nodes.ground.geometry} material={materials['Realistic Water with Depth Darkness']} position={[1.22, 0, 6.92]} scale={50} />
      <mesh geometry={nodes.Cube.geometry} position={[64.665, 1, 10.648]} scale={[36.05, 1, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube001.geometry} position={[28.225, 4.36, 10.648]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Plane.geometry} position={[62.806, 0.2, 0.648]} scale={[38.31, 1, 10.98]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube002.geometry} position={[64.545, 4.36, 10.648]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube003.geometry} position={[99.735, 4.36, 10.648]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube004.geometry} position={[64.665, 1, -9.772]} scale={[36.05, 1, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube005.geometry} position={[28.225, 4.36, -9.882]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube006.geometry} position={[64.545, 4.36, -9.882]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Cube007.geometry} position={[99.735, 4.36, -9.882]} scale={[0.99, 4.26, 1]}>
        <meshStandardMaterial {...RoadTexture} />
      </mesh>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[28.225, 9.73, 10.648]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={5}/>
        <pointLight color={'orange'} intensity={400} />
      </mesh>
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[64.545, 9.73, 10.648]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={5}/>
        <pointLight color={'orange'} intensity={400}/>
      </mesh>
      <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[99.735, 9.73, 10.648]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={5}/>
        <pointLight color={'orange'} intensity={400}/>
      </mesh>
      <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[99.735, 9.73, -9.882]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={5}/>
        <pointLight color={'orange'} intensity={400}/>
      </mesh>
      <mesh geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[64.545, 9.73, -9.882]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={5}/>
        <pointLight color={'orange'} intensity={400}/>
      </mesh>
      <mesh geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[28.225, 9.73, -9.882]} scale={0.5}>
        <meshStandardMaterial color={'orange'} emissive={'orange'} emissiveIntensity={20}/>
        <pointLight color={'orange'} intensity={400}/>
      </mesh>
      <mesh geometry={nodes.tree_ground.geometry} position={[-0.164, 0, 0.838]} scale={[30, 5, 30]}>
        <meshStandardMaterial {...GrassTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Sakura_Tree_7.glb')
